name: Deploy standalone plugins to WordPress.org

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      slug:
        type: string
        description: 'The slug of the plugin to deploy'
      dry-run:
        type: boolean
        description: 'Debug mode (run without publishing).'
        default: false

jobs:
  pre-run:
    name: Pre-run
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.json }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Get directory
        id: get-plugin-directory
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "directory=$(node ./bin/plugin/cli.js get-plugin-dir --slug=${{ inputs.slug }})" >> $GITHUB_OUTPUT

      - name: Set matrix
        id: set-matrix
        run: |
          PLUGINS=$(jq -r '.plugins' plugins.json)
          if ${{ github.event_name == 'workflow_dispatch' }}; then
            SLUG=${{ inputs.slug }}

            # Check if the slug is valid
            if [[ ! " $PLUGINS " =~ " $SLUG " ]]; then
              echo "Invalid slug: $SLUG"
              exit 1
            fi

            PLUGINS="[ \"$SLUG\" ]"
          fi

          # Set the matrix
          echo "json=$(echo $PLUGINS | jq -c .)" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy Plugin
    needs: pre-run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plugin: ${{ fromJSON(needs.pre-run.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install npm dependencies
        run: npm

      - name: Building standalone plugin
        run: npm run build:plugin:${{ matrix.plugin }}

      - name: Deploy Standalone Plugin - ${{ matrix.plugin }}
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          dry-run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run || false }}
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: ${{ matrix.plugin }}
          BUILD_DIR: ./build/${{ matrix.plugin }}
          ASSETS_DIR: ./plugins/${{ matrix.plugin }}/.wordpress-org
