---
name: Deploy Standalone Plugin(s) to WordPress.org

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      plugin:
        type: string
        description: 'The slug of the plugin to deploy'
        required: true
      dry-run:
        type: boolean
        description: 'Debug mode (run without publishing).'
        default: false

permissions: {}

jobs:
  pre-run:
    name: Pre-run
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.plugins }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set matrix
        id: set-matrix
        run: |
          PLUGINS=$(jq -r '.plugins' plugins.json)
          if ${{ github.event_name == 'workflow_dispatch' }}; then
            SLUG=${{ inputs.plugin }}
            if echo $PLUGINS | jq -e '.[] | select(. == "'$SLUG'")' > /dev/null; then
              PLUGINS="[ \"$SLUG\" ]"
            else
              echo "::error::The plugin $SLUG is not in the list of plugins to deploy."
              exit 1
            fi
          fi

          # Set the matrix.
          echo "::notice::Deploying the following plugins: $PLUGINS"
          echo "plugins=$(echo $PLUGINS | jq -c .)" >> $GITHUB_OUTPUT

  deploy:
    name: "Deploy Plugin: ${{ matrix.plugin }}"
    needs: pre-run
    runs-on: ubuntu-latest
    permissions:
      actions: write
      deployments: write
    strategy:
      matrix:
        plugin: ${{ fromJSON(needs.pre-run.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build:plugin:${{ matrix.plugin }}

      - name: Set plugin version
        working-directory: ./build
        run: |
          echo "PLUGIN_VERSION=$(jq -r '."${{ matrix.plugin }}"' manifest.json)" >> $GITHUB_ENV

      - name: Create zip file
        run: |
          mkdir -p ./build/dist
          cd ./build/${{ matrix.plugin }}
          zip -r ../dist/${{ matrix.plugin }}.zip .

      - name: Generate checksum
        working-directory: ./build/dist
        run: |
          mkdir -p $RUNNER_TEMP/plugin-checksums
          find . -type f -print0 | sort -z | xargs -r0 shasum -a 256 -b | sed 's# \*\./# *#' > $RUNNER_TEMP/plugin-checksums/checksums.txt
          shasum -a 256 -U -c $RUNNER_TEMP/plugin-checksums/checksums.txt
          cat $RUNNER_TEMP/plugin-checksums/checksums.txt | while read sum file; do echo "$sum $file" > ${file#\*}.sha256; done

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.plugin }}
          path: ./build/dist

      - name: Start deployment
        uses: bobheadxi/deployments@v1
        id: wporg-deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: "wp.org plugin: ${{ matrix.plugin }}"

      - name: Deploy Plugin - ${{ matrix.plugin }}
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          dry-run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run || false }}
        env:
          SLUG: ${{ matrix.plugin }}
          VERSION: ${{ env.PLUGIN_VERSION }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          BUILD_DIR: ./build/${{ matrix.plugin }}
          ASSETS_DIR: ./plugins/${{ matrix.plugin }}/.wordpress-org

      - name: Finish deployment
        if: always()
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.wporg-deployment.outputs.deployment_id }}
          env: "wp.org plugin: ${{ matrix.plugin }}"
          env_url: "https://wordpress.org/plugins/${{ matrix.plugin }}/"

  release-assets:
    name: Add release assets
    needs: [ pre-run, deploy ]
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    if: github.event_name == 'release'
    strategy:
      matrix:
        plugin: ${{ fromJSON(needs.pre-run.outputs.matrix) }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.plugin }}
          path: ./build/dist

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/dist/${{ matrix.plugin }}.zip
            ./build/dist/${{ matrix.plugin }}.zip.sha256
